### ISSUE TITLE
Would you like an additional maintainer?

### ISSUE THREAD

**Issue by TimothyJones** [tvdstaaij/node-git-describe#18]
Hi there! I've noticed that this repository hasn't had any changes in a few years - would you like a hand maintaining it? 

Over the last few months, I've opened a couple of small issues (#16 and #17), which I would be happy to help fix. Additionally, it would be excellent to get #13 merged and released so that the vulnerability warning goes away. I'm depending on this package in a tool I'm using to generate human-friendly prerelease output (`absolute-version`, check it out [here](https://github.com/pact-foundation/absolute-version-js)), so it feels appropriate to contribute back rather than fork it.

I know that maintaining open source is a lot of work (even for small changes), so I'd be happy to help out.

**Comment by tvdstaaij** [comment]
Sure, that would be great! Lack of time is indeed the main reason I haven't done much on github lately. But I've worked with enough open source software to agree that it's always a shame when it's necessary to hard-fork modules for minor issues just because the maintainer is unresponsive. I also have to admit that when I first published this I didn't foresee this being depended on as much as it ended up doing.

So anyway, I'll add you as a maintainer as soon as I figure out how. I would prefer to keep publishing to npm myself for the time being, but I should be able to do that in a timely fashion. Would this work as a release procedure?

1. Create release branch, e.g. `release/vx.y.z`
2. Bump versions and commit other release chores (if any) on release branch
3. PR release branch to master, add other maintainer(s) as reviewer
4. When it's approved, I'll merge and publish to npm

**Comment by TimothyJones** [comment]
Yes, that process sounds great! I'm very happy not to have npm permissions.

I've also noticed that the builds were in travis - but unfortunately travis no longer build open source projects so easily. We have migrated a number of the pact-foundation projects to build on github actions - I can do that here as well if you like.

> I also have to admit that when I first published this I didn't foresee this being depended on as much as it ended up doing.

Haha! Yes, it's always the projects you don't expect 😂

**Comment by tvdstaaij** [comment]
Oh, I wasn't aware that Travis changed their free service. Back when I set it up it was the hot thing and IIRC Github Actions didn't exist yet, or maybe only in alpha/beta form. But yeah migrating to Actions sounds good, especially because it means fewer external dependencies.

I believe you should have received an invite to become collaborator with direct access on this repository.

**Comment by TimothyJones** [comment]
I have! It's late here, but I should have some time to put a branch together for you to review tomorrow.

If you're short on time, you might be interested in tools to reduce the release chores - I quite like [standard-version](https://github.com/conventional-changelog/standard-version) which generates changelogs and the appropriate version bump, git commit + git tag automatically, as long as commits are in the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) style. I can also introduce that if you like?

**Comment by TimothyJones** [comment]
Also, thanks for the prompt reply to my suggestion! Very much appreciated!

**Comment by tvdstaaij** [comment]
> I quite like standard-version which generates changelogs and the appropriate version bump, git commit + git tag automatically, as long as commits are in the conventional commit style. I can also introduce that if you like?

Sure, sounds good.

> I have! It's late here, but I should have some time to put a branch together for you to review tomorrow.

No hurry! I may be short on time but I don't expect to disappear anytime soon.

**Comment by TimothyJones** [comment]
🙌
